### ISSUE TITLE
タイトル画面 機能追加

### ISSUE THREAD

**Issue by makochang** [makochang/FreeForAll#13]
決定ボタンがわからないので、ヘルプテキストを追加する。ラベルは「Bボタンで決定」。
決定ボタンを押してから、次の画面に遷移するまで待ち時間が発生する場合がある。ユーザーが決定できたかわからないので、「Now Loading」を表示する。

- [x] Bボタンで決定テキストを追加
- [ ] Bボタンが押されたら「Now Loading」を表示

**Comment by nature5884** [comment]
NowLoading表示はシングルプレイ時のみでいいですか？

**Comment by makochang** [comment]
マルチプレイも両方必要です。
