### ISSUE TITLE
気になったところリスト

### ISSUE THREAD

**Issue by ryoten82** [makochang/FreeForAll#2]
・起動後、途中からマウス操作になってしまう。
・死亡時、仮でいいので何かエフェクトが欲しい（ダウンと死亡の差が分かりにくい）
・試合開始のＵＩが欲しい。
・試合終了後のリザルトが欲しい（簡易表彰台のようなもの）
・スーパーアーマー実装可能であれば追加希望。
・ディガベルにダウンモーション無い？
・ガードしたままジャンプするとガードモーションのまま飛ぶ。
・ジャンプした際、空中で移動方向を変えられるようにしたい。

**Comment by H-Kuramoto** [comment]
ディガベル対応済み

**Comment by makochang** [comment]
個別のIssueに分割したためクローズ
